### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by RyanSnodgrass**

### CODE REVIEW

**Comment by EvanGranthamBrown** [comment]
It appears that eslint wants to slap a "const" on anything which is assigned once and never modified. However, many of these things aren't actually constants (their values are not known before the code runs). For example, in javascripts/common.js, we have:

**const pathSplit = window.location.pathname.split('/').filter(function (str) { return str; });**

Not only is pathSplit not known until the code runs, but the const keyword does not really guarantee immutability for arrays and hashes. You can do this and it works:

**pathSplit.push('some new string');**

Can we refine/limit what eslint wants to constantize?

**Comment by RyanSnodgrass** [comment]
@EvanGranthamBrown The `var` keyword is going out the door more and more. The new es6 javascript standard defines `let` as variables that are mutable and `const` as immutable. There are instances where the `var` keyword can jump scope and has some additional quirks.

Here's a [blog post](https://blog.mariusschulz.com/2015/12/31/constant-variables-in-javascript-or-when-const-isnt-constant) about it .  He describes `const` not as a CONSTANT but as one time assignment. Attempts to reassign pathSplit results in `VM282:1 Uncaught TypeError: Assignment to constant variable.`

This is the style that airbnb suggests. Personally, I like it. It makes comprehension faster knowing which variables are changing and which are not. If we don't like it, we can turn off that lint

**Comment by EvanGranthamBrown** [comment]
Okay, we can stick with airbnb's style; no need to turn off that lint. If that's how const is meant to be used in JS, then that's how we should use it.

(Adding "const != constant" to my list of gripes about Javascript. Now if you'll excuse me, I have to yell at some kids to get off my lawn.)

**Comment by RyanSnodgrass** [comment]
Are we ok with this pull request?

**Pull request merged**
